//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnicaesGestion
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompetenciaPuestoTrabajo
    {
        public int Id { get; set; }
        public int idCompetencia { get; set; }
        public int idPuestoTrabajo { get; set; }
        public bool escencial { get; set; }
    
        public virtual CatalogoCompetencia CatalogoCompetencia { get; set; }
        public virtual PuestoTrabajo PuestoTrabajo { get; set; }
    }
}
