//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnicaesGestion
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompetenciaPuestoTrabajo
    {
        public int Id { get; set; }
        public int idCompetencia { get; set; }
        public int idPuestoTrabajo { get; set; }
        public bool escencial { get; set; }
    
        public virtual CatalogoCompetencia CatalogoCompetencia { get; set; }
        public virtual PuestoTrabajo PuestoTrabajo { get; set; }
    }
}
