//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnicaesGestion
{
    using System;
    using System.Collections.Generic;
    
    public partial class Credential
    {
        public int idPersonal { get; set; }
        public string user { get; set; }
        public string password { get; set; }
        public bool enable { get; set; }
        public bool reset { get; set; }
        public int idRol { get; set; }
    
        public virtual Personal Personal { get; set; }
        public virtual Role Role { get; set; }
    }
}
