//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnicaesGestion
{
    using System;
    using System.Collections.Generic;
    
    public partial class FuncionUnidad
    {
        public int id { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> idUnidad { get; set; }
    
        public virtual Unidad Unidad { get; set; }
    }
}
