//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnicaesGestion
{
    using System;
    using System.Collections.Generic;
    
    public partial class FuncionPuestoTrabajo
    {
        public int id { get; set; }
        public string funcion { get; set; }
        public Nullable<int> idPuestoTrabajo { get; set; }
    
        public virtual PuestoTrabajo PuestoTrabajo { get; set; }
    }
}
