//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnicaesGestion
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paso
    {
        public int id { get; set; }
        public int numero { get; set; }
        public string descripcion { get; set; }
        public string predecesores { get; set; }
        public int idProcedimiento { get; set; }
        public Nullable<int> idTipoPaso { get; set; }
        public Nullable<int> idPuestoTrabajo { get; set; }
    
        public virtual Procedimiento Procedimiento { get; set; }
        public virtual PuestoTrabajo PuestoTrabajo { get; set; }
        public virtual TipoPaso TipoPaso { get; set; }
    }
}
