//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnicaesGestion
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paso
    {
        public int id { get; set; }
        public int numero { get; set; }
        public string descripcion { get; set; }
        public string predecesores { get; set; }
        public int idProcedimiento { get; set; }
        public Nullable<int> idTipoPaso { get; set; }
        public Nullable<int> idPuestoTrabajo { get; set; }
    
        public virtual Procedimiento Procedimiento { get; set; }
        public virtual PuestoTrabajo PuestoTrabajo { get; set; }
        public virtual TipoPaso TipoPaso { get; set; }
    }
}
