//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnicaesGestion
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requisito
    {
        public int id { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> idPuestoTrabajo { get; set; }
        public Nullable<int> idCategoria { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        public virtual PuestoTrabajo PuestoTrabajo { get; set; }
    }
}
