//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnicaesGestion
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requisito
    {
        public int id { get; set; }
        public string denominacion { get; set; }
        public Nullable<int> idTipoRequisito { get; set; }
        public Nullable<int> idcriterios { get; set; }
        public Nullable<int> idPrioridadRequisito { get; set; }
        public Nullable<int> idPerfilContratacion { get; set; }
    
        public virtual Criterio Criterio { get; set; }
        public virtual PerfilContratacion PerfilContratacion { get; set; }
        public virtual PrioridadRequisito PrioridadRequisito { get; set; }
        public virtual TipoRequisito TipoRequisito { get; set; }
    }
}
